name = "isqrt-lean4"
lintDriver = "batteries/runLinter"
defaultTargets = ["Isqrt", "IsqrtTests", "isqrt"]

[leanOptions]
autoImplicit = false

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4"
rev = "v4.30.0"

[[lean_lib]]
name = "Isqrt"

[[lean_lib]]
name = "IsqrtTests"

[[lean_exe]]
name = "isqrt"
root = "Main"
